baseurl = "https://example.org/"
languageCode = "en-us"
title = "Austin Black Label"
# Define how many pages appear per site
paginate = 10
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"

[params]
    site_author = "CS Web Design"
    site_description = "First Hugo website."
    location = "Austin, TX"
    # Link custom assets relative to /static
    avatar = "img/profile-image.png"
    header_background = "img/desk.jpg"
    header_title = "The Header"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "CSWebDesign"
    facebook  = "CSWebDesign"
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "CSWebDesign"
    gplus     = ""
